apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:

    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets:
        - name: ecr-credentials
      containers:
        - name: frontend
          image: 357938784857.dkr.ecr.eu-north-1.amazonaws.com/portfolio-frontend:7397261f23e6260014ee8d21cc6d08a9a7de31b9
          ports:
            - containerPort: 80
